import { Head, Html, Main, NextScript } from 'next/document'

/* NOTE: This imports custom google font: see https://nextjs.org/docs/advanced-features/custom-document */
export default function Document() {
  return (
    <Html>
      <Head>
        <meta content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
