# Specify current major version of docker compose.
# See https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3'

services:
  # Define a service for the Next.js application.
  nextjs:
    build: ./app
    command: ["yarn", "dev"]
    environment:
      # Comment out the next line to test connecting with the API.
      - NEXT_PUBLIC_DEMO_MODE=true
    ports:
      # Expose a port to access the application.
      - 3000:3000
      # Expose a port for storybook.
      - 6006:6006
    volumes:
      # Mount the app directory for faster local development.
      - ./app:/srv
      # Use a named volume for the node_modules so that the container uses the guest machine's node_modules dir instead of the host machine's node_modules directory, which might be divergent.
      - nextjs_nodemodules:/srv/node_modules

volumes:
  nextjs_nodemodules:
